extends:
  - recommended

rules:
  operation-operationId: error
  no-unresolved-refs: error
  no-ambiguous-paths: error
  no-unused-components: warn
  info-license: off
  no-server-example.com: off
  operation-4xx-response: off
